name: CI

on:
  push:
    branches: [ master, main ]
    tags: [ 'v*' ]   # <— au lieu de on.create
#  create:
#    tags:          # ❌ supprime ça

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0   # on veut les tags

      - name: work around permission issue
        run: git config --global --add safe.directory /srv

      - name: Create revision
        run: make revision.tex

      - name: Build docker images
        run: docker build . -t local -f .devcontainer/Dockerfile

      - name: Build
        run: docker run -v "$GITHUB_WORKSPACE":/srv -w /srv local make

      - name: Upload refcard.pdf
        uses: actions/upload-artifact@v4
        with:
          name: refcard
          path: refcard.pdf
          if-no-files-found: error

      - name: Upload preview.png
        uses: actions/upload-artifact@v4
        with:
          name: preview
          path: preview.png
          if-no-files-found: error

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write
    steps:
      - name: Download refcard
        uses: actions/download-artifact@v4
        with:
          name: refcard
          path: dist

      - name: Download preview
        uses: actions/download-artifact@v4
        with:
          name: preview
          path: dist

      - name: Create/Update Release with assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/refcard.pdf
            dist/preview.png
          generate_release_notes: true
